### ISSUE TITLE
未知崩溃

### ISSUE THREAD

**Issue by localhosts-A** [HMCL-dev/HMCL-PE-CN#14]
报错提示如下
Build version: 1.0 
Build date: 1981-01-01 01:01:02 
Current date: 2022-05-04 18:05:20 
Device: Xiaomi MIX 2S 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at com.tungsten.hmclpe.launcher.launch.check.CheckAccountTask.lambda$doInBackground$0$com-tungsten-hmclpe-launcher-launch-check-CheckAccountTask(CheckAccountTask.java:97)
	at com.tungsten.hmclpe.launcher.launch.check.CheckAccountTask$$ExternalSyntheticLambda2.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:7589)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by Tungstend** [comment]
这个已经解决了，你用的是澪u内测群的，今天下午才解决的这个bug，目前只在HMCLPE 内测群发了
