### ISSUE TITLE
1.7.10boat端NEI无法使用

### ISSUE THREAD

**Issue by T-CATHOME** [HMCL-dev/HMCL-PE-CN#33]

**Comment by T-CATHOME** [comment]
<details>
<summary>boat_latest_log.txt</summary>

```
OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
[authlib-injector] [INFO] Logging file: /storage/emulated/0/HMCLPE/.minecraft/versions/Forge-1.7.10/authlib-injector.log
[authlib-injector] [INFO] Version: 1.1.45
[authlib-injector] [INFO] Authentication server: http://localhost:37463
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
[touch-injector] [INFO] Logging file: /storage/emulated/0/HMCLPE/.minecraft/versions/Forge-1.7.10/touch-injector.log
[touch-injector] [INFO] Version: 1.1.30
[authlib-injector] [INFO] Httpd is running on port 39163
[authlib-injector] [INFO] Transformed [com.mojang.patchy.BlockedServers] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [Callback Metafactory Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [Class File Version Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Yggdrasil Public Key Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Callback Metafactory Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Class File Version Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication] with [Constant URL Transformer]
[03:09:30] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[03:09:30] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[03:09:30] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[03:09:31] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[03:09:31] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0-internal, running on Linux:aarch64:4.4.291-Predator-Stormbreaker-X4.10-g6b2d06a28f39, installed at /data/data/com.tungsten.hmclpe/app_runtime/java/default
[03:09:31] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from b[工具&优化]OptiFine_HD_E7.jar
[03:09:31] [main/WARN]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.UnsatisfiedLinkError: java.awt.Component.initIDs()V
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.awt.Component.initIDs(Native Method)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.awt.Component.<clinit>(Component.java:596)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.DepLoader$DepLoadInst.loadDeps(DepLoader.java:460)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:449)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.DepLoader.load(DepLoader.java:584)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Class.newInstance(Class.java:442)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[03:09:31] [main/ERROR]: An error occurred trying to configure the minecraft home at /storage/emulated/0/HMCLPE/.minecraft/versions/Forge-1.7.10 for Forge Mod Loader
java.lang.UnsatisfiedLinkError: java.awt.Component.initIDs()V
	at java.awt.Component.initIDs(Native Method) ~[?:1.8.0-internal]
	at java.awt.Component.<clinit>(Component.java:596) ~[?:1.8.0-internal]
	at codechicken.core.launch.DepLoader$DepLoadInst.loadDeps(DepLoader.java:460) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:449) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader.load(DepLoader.java:584) ~[DepLoader.class:?]
	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47) ~[CodeChickenCore-1.7.10-1.0.7.46-universal.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0-internal]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0-internal]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0-internal]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Exception in thread "main" [03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.UnsatisfiedLinkError: java.awt.Component.initIDs()V
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.awt.Component.initIDs(Native Method)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.awt.Component.<clinit>(Component.java:596)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.DepLoader$DepLoadInst.loadDeps(DepLoader.java:460)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:449)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.DepLoader.load(DepLoader.java:584)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Class.newInstance(Class.java:442)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[03:09:31] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
</details>
