### ISSUE TITLE
Can play versions

### ISSUE THREAD

**Issue by TheBestXann** [HMCL-dev/HMCL-PE-CN#52]
Build version: 1.0 
Build date: 1981-01-01 01:01:02 
Current date: 2022-08-01 18:38:05 
Device: Samsung SM-A127F 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.NumberFormatException: For input string: "350164a953097349904a8e516418c3"
	at java.lang.Long.parseLong(Long.java:597)
	at java.lang.Long.valueOf(Long.java:781)
	at java.lang.Long.decode(Long.java:933)
	at java.util.UUID.fromString(UUID.java:206)
	at com.tungsten.hmclpe.utils.gson.UUIDTypeAdapter.fromString(UUIDTypeAdapter.java:38)
	at com.tungsten.hmclpe.launcher.launch.AccountPatch.getAccountArgs(AccountPatch.java:49)
	at com.tungsten.hmclpe.launcher.launch.check.LaunchTask.doInBackground(LaunchTask.java:32)
	at com.tungsten.hmclpe.launcher.launch.check.LaunchTask.doInBackground(LaunchTask.java:12)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by ssaagamemer** [comment]
you typed wrong its requried - in uuid
